version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts-alpine
    hostname: jenkins.172-27-11-10.nip.io
    user: root
    entrypoint:
    - sh
    - -c
    - 'apk add --no-cache docker && su -c "/sbin/tini -- /usr/local/bin/jenkins.sh" jenkins'
    deploy:
      labels:
      - "traefik.http.routers.jenkins.rule=Host(`jenkins.172-27-11-10.nip.io`)"
      - "traefik.http.services.jenkins.loadbalancer.server.port=8080"
    volumes:
    - jenkins:/var/jenkins_home
    networks:
    - jenkins
    - traefik_traefik
  gitea:
    image: gitea/gitea:1.11.3
    hostname: gitea.172-27-11-10.nip.io
    deploy:
      labels:
      - "traefik.http.routers.gitea.rule=Host(`gitea.172-27-11-10.nip.io`)"
      - "traefik.http.services.gitea.loadbalancer.server.port=3000"
    networks:
    - traefik_traefik
    volumes:
    - gitea:/data

volumes:
  jenkins:
    driver_opts:
      type: nfs
      o: addr=172.27.11.40,nolock,soft,rw
      device: ':/srv/nfs/v1'
  gitea:
    driver_opts:
      type: nfs
      o: addr=172.27.11.40,nolock,soft,rw
      device: ':/srv/nfs/v2'

networks:
  traefik_traefik:
    external: true
  jenkins:
