version: '3'

services:
  perl:
    image: hectorvido/dancer
    environment:
    - REDIS_SERVER=redis
    - REDIS_PORT=6379
    deploy:
      labels:
      - "traefik.http.routers.dancer.rule=Host(`dancer.172-27-11-10.nip.io`)"
      - "traefik.http.services.dancer.loadbalancer.server.port=5000"
    networks:
    - traefik_traefik
    - dancer
  redis:
    image: redis:alpine
    networks:
    - dancer

networks:
  traefik_traefik:
    external: true
  dancer:
