version: '3'

services:
  reverse-proxy:
    image: traefik:v2.2
    command:
    - --api.insecure=true
    - --providers.docker.swarmMode=true
    - --providers.docker.endpoint=unix:///var/run/docker.sock
    - --providers.docker.network=traefik_traefik
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      placement:
        constraints:
        - node.role == manager
    networks:
    - traefik

networks:
  traefik:
